[theme]
base = "dark"
primaryColor = "#F63366"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "monospace"

[ui]
hide_sidebar_nav = true

[client]
showSidebarNavigation = false